import React, { Component } from 'react';
import {Field, reduxForm, FieldArray} from 'redux-form';


const renderTags =({ fields}) =>
<ul>
 <button type="button" onClick={() => fields.push()}> Add new Tag </button>
  {
    fields.map ((field, index) =>
      <li key = {index}>
      <Field name = {field} component ="input" placeholder="Tag"/>
      <button type="button" onClick ={() => fields.remove (index)} > Remove </button>
      </li>
  )}
</ul>
class LinkForm extends Component{
 render (){
  return(
    <div class= "container">
    <form onSubmit={this.props.handleSubmit}>
      <div>
          <label> Title </label>
          <div>
            <Field name="Title"
            component="input"
            type="text"
            placeholder="Enter Title"/>
          </div>

      </div>
      <div>
          <label> Link </label>
          <div>
            <Field name="Link"
            component="Input"
            type="text"
            placeholder="Enter URL" />
          </div>

      </div>
      <div>
          <label> Preview </label>
          <div>
            <Field name="Preview"
            component="textarea"
            type="text"
            placeholder="Preview Text (autogenerated)" />
          </div>

      </div>
      <div>
        <FieldArray name="tags" component={renderTags}/>
        </div>
      <div>
        <button type="submit">Find</button>
      </div>
    </form>
    </div>
    );
  }
}
LinkForm = reduxForm({
  form:'content'
})(LinkForm)
export default LinkForm;
